// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viariato.Infrastructure;

#nullable disable

namespace Viariato.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905202856_AddFlujoEstadoDef")]
    partial class AddFlujoEstadoDef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viariato.Infrastructure.Trabajos.Trabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("ParentTrabajoId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_trabajo_id");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("process_code");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_type");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_trabajos");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_trabajos_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Data"), "gin");

                    b.HasIndex("ParentTrabajoId")
                        .HasDatabaseName("ix_trabajos_parent_trabajo_id");

                    b.HasIndex("ProcessCode")
                        .HasDatabaseName("ix_trabajos_process_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_trabajos_status");

                    b.HasIndex("SubjectType", "SubjectKey")
                        .HasDatabaseName("ix_trabajos_subject_type_subject_key");

                    b.ToTable("trabajos", "ops");
                });

            modelBuilder.Entity("Viariato.Infrastructure.Trabajos.TrabajoLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("TrabajoId")
                        .HasColumnType("uuid")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_trabajo_logs");

                    b.HasIndex("TrabajoId", "Timestamp")
                        .HasDatabaseName("ix_trabajo_logs_trabajo_id_timestamp");

                    b.ToTable("trabajo_logs", "ops");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.AgenteEjecucionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DecisionesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("decisiones_json");

                    b.Property<Guid>("EjecucionPasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_paso_id");

                    b.Property<string>("HerramientasUsadas")
                        .HasColumnType("jsonb")
                        .HasColumnName("herramientas_usadas");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_snapshot");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("OutputSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_agente_ejecucion_detalles");

                    b.HasIndex("EjecucionPasoId")
                        .IsUnique()
                        .HasDatabaseName("ix_agente_ejecucion_detalles_ejecucion_paso_id");

                    b.ToTable("agente_ejecucion_detalles", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Caso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DatosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_json");

                    b.Property<Guid?>("EjecucionActualId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_actual_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("EstadoNegocioActualId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_negocio_actual_id");

                    b.Property<Guid>("FlujoId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_id");

                    b.Property<Guid>("FlujoVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_version_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_casos");

                    b.HasIndex("DatosJson")
                        .HasDatabaseName("ix_casos_datos_json");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DatosJson"), "gin");

                    b.HasIndex("EjecucionActualId")
                        .HasDatabaseName("ix_casos_ejecucion_actual_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_casos_estado");

                    b.HasIndex("EstadoNegocioActualId")
                        .HasDatabaseName("ix_casos_estado_negocio_actual_id");

                    b.HasIndex("FlujoId")
                        .HasDatabaseName("ix_casos_flujo_id");

                    b.HasIndex("FlujoVersionId")
                        .HasDatabaseName("ix_casos_flujo_version_id");

                    b.ToTable("casos", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.CasoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_json");

                    b.Property<Guid?>("EjecucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_caso_eventos");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_caso_eventos_caso_id");

                    b.HasIndex("EjecucionId")
                        .HasDatabaseName("ix_caso_eventos_ejecucion_id");

                    b.ToTable("caso_eventos", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EjecucionPasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_paso_id");

                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_documentos_caso_id");

                    b.HasIndex("EjecucionPasoId")
                        .HasDatabaseName("ix_documentos_ejecucion_paso_id");

                    b.ToTable("documentos", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Ejecucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("FlujoVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_version_id");

                    b.Property<Guid?>("PasoActualId")
                        .HasColumnType("uuid")
                        .HasColumnName("paso_actual_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_ejecuciones");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_ejecuciones_caso_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_ejecuciones_estado");

                    b.HasIndex("FlujoVersionId")
                        .HasDatabaseName("ix_ejecuciones_flujo_version_id");

                    b.HasIndex("PasoActualId")
                        .HasDatabaseName("ix_ejecuciones_paso_actual_id");

                    b.ToTable("ejecuciones", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.EjecucionPaso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EjecucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_id");

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("text")
                        .HasColumnName("error_mensaje");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("FlujoPasoDefId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_paso_def_id");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("integer")
                        .HasColumnName("numero_intento");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TipoPaso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_paso");

                    b.Property<Guid?>("TrabajoId")
                        .HasColumnType("uuid")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id")
                        .HasName("pk_ejecucion_pasos");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_ejecucion_pasos_caso_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_ejecucion_pasos_estado");

                    b.HasIndex("FlujoPasoDefId")
                        .HasDatabaseName("ix_ejecucion_pasos_flujo_paso_def_id");

                    b.HasIndex("TrabajoId")
                        .HasDatabaseName("ix_ejecucion_pasos_trabajo_id");

                    b.HasIndex("EjecucionId", "FlujoPasoDefId")
                        .HasDatabaseName("ix_ejecucion_pasos_ejecucion_id_flujo_paso_def_id");

                    b.HasIndex("EjecucionId", "FlujoPasoDefId", "NumeroIntento")
                        .IsUnique()
                        .HasDatabaseName("ix_ejecucion_pasos_ejecucion_id_flujo_paso_def_id_numero_inten");

                    b.ToTable("ejecucion_pasos", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("caso_id");

                    b.Property<string>("ContenidoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("contenido_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<Guid>("EjecucionPasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_paso_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_evidencias");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("ix_evidencias_caso_id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_evidencias_documento_id");

                    b.HasIndex("EjecucionPasoId")
                        .HasDatabaseName("ix_evidencias_ejecucion_paso_id");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_evidencias_tipo");

                    b.ToTable("evidencias", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.RevisionHumana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("EjecucionPasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_paso_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RevisorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revisor_user_id");

                    b.HasKey("Id")
                        .HasName("pk_revisiones_humanas");

                    b.HasIndex("EjecucionPasoId")
                        .IsUnique()
                        .HasDatabaseName("ix_revisiones_humanas_ejecucion_paso_id");

                    b.ToTable("revisiones_humanas", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.RpaEjecucionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AplicacionObjetivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aplicacion_objetivo");

                    b.Property<Guid>("EjecucionPasoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_paso_id");

                    b.Property<string>("ParametrosEntrada")
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros_entrada");

                    b.Property<string>("ParametrosSalida")
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros_salida");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_rpa_ejecucion_detalles");

                    b.HasIndex("EjecucionPasoId")
                        .IsUnique()
                        .HasDatabaseName("ix_rpa_ejecucion_detalles_ejecucion_paso_id");

                    b.ToTable("rpa_ejecucion_detalles", "casos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.AgenteDefinicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("HerramientasPermitidas")
                        .HasColumnType("jsonb")
                        .HasColumnName("herramientas_permitidas");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("ParametrosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros_json");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agente_definiciones");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_agente_definiciones_nombre");

                    b.ToTable("agente_definiciones", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.AsignacionFlujo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("FlujoId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asignaciones_flujo");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asignaciones_flujo_user_id");

                    b.HasIndex("FlujoId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_asignaciones_flujo_flujo_id_user_id");

                    b.ToTable("asignaciones_flujo", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.Flujo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VersionActivaId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_activa_id");

                    b.HasKey("Id")
                        .HasName("pk_flujos");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_flujos_nombre");

                    b.HasIndex("VersionActivaId")
                        .HasDatabaseName("ix_flujos_version_activa_id");

                    b.ToTable("flujos", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoEstadoDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display");

                    b.Property<Guid>("FlujoId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flujo_estado_defs");

                    b.HasIndex("FlujoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_flujo_estado_defs_flujo_id_codigo");

                    b.ToTable("flujo_estado_defs", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoPasoDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgenteDefinicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("agente_definicion_id");

                    b.Property<string>("ConfiguracionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracion_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlujoVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_version_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("TipoPaso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_paso");

                    b.HasKey("Id")
                        .HasName("pk_flujo_paso_defs");

                    b.HasIndex("AgenteDefinicionId")
                        .HasDatabaseName("ix_flujo_paso_defs_agente_definicion_id");

                    b.HasIndex("FlujoVersionId")
                        .HasDatabaseName("ix_flujo_paso_defs_flujo_version_id");

                    b.HasIndex("TipoPaso")
                        .HasDatabaseName("ix_flujo_paso_defs_tipo_paso");

                    b.HasIndex("FlujoVersionId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_flujo_paso_defs_flujo_version_id_orden");

                    b.ToTable("flujo_paso_defs", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("FlujoId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_id");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer")
                        .HasColumnName("numero_version");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_flujo_versiones");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_flujo_versiones_estado");

                    b.HasIndex("FlujoId")
                        .HasDatabaseName("ix_flujo_versiones_flujo_id");

                    b.HasIndex("FlujoId", "NumeroVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_flujo_versiones_flujo_id_numero_version");

                    b.ToTable("flujo_versiones", "flujos");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("ReplacedById")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.RoleAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_audit_log");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_role_audit_log_target_user_id");

                    b.ToTable("role_audit_log", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_normalized");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_normalized");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("Viariato.Infrastructure.Trabajos.Trabajo", b =>
                {
                    b.HasOne("Viariato.Infrastructure.Trabajos.Trabajo", "ParentTrabajo")
                        .WithMany()
                        .HasForeignKey("ParentTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_trabajos_trabajos_parent_trabajo_id");

                    b.Navigation("ParentTrabajo");
                });

            modelBuilder.Entity("Viariato.Infrastructure.Trabajos.TrabajoLog", b =>
                {
                    b.HasOne("Viariato.Infrastructure.Trabajos.Trabajo", "Trabajo")
                        .WithMany()
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trabajo_logs_trabajos_trabajo_id");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.AgenteEjecucionDetalle", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", "EjecucionPaso")
                        .WithMany()
                        .HasForeignKey("EjecucionPasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agente_ejecucion_detalles_ejecucion_paso_ejecucion_paso_id");

                    b.Navigation("EjecucionPaso");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Caso", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Ejecucion", "EjecucionActual")
                        .WithMany()
                        .HasForeignKey("EjecucionActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_casos_ejecucion_ejecucion_actual_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoEstadoDef", "EstadoNegocioActual")
                        .WithMany()
                        .HasForeignKey("EstadoNegocioActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_casos_flujo_estado_defs_estado_negocio_actual_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.Flujo", null)
                        .WithMany()
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_casos_flujos_flujo_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoVersion", null)
                        .WithMany()
                        .HasForeignKey("FlujoVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_casos_flujo_versiones_flujo_version_id");

                    b.Navigation("EjecucionActual");

                    b.Navigation("EstadoNegocioActual");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.CasoEvento", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Caso", null)
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caso_eventos_casos_caso_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.Ejecucion", null)
                        .WithMany()
                        .HasForeignKey("EjecucionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_caso_eventos_ejecucion_ejecucion_id");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Documento", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Caso", null)
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_casos_caso_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", null)
                        .WithMany()
                        .HasForeignKey("EjecucionPasoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documentos_ejecucion_paso_ejecucion_paso_id");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Ejecucion", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Caso", "Caso")
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ejecuciones_casos_caso_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoVersion", null)
                        .WithMany()
                        .HasForeignKey("FlujoVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejecuciones_flujo_versiones_flujo_version_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", "PasoActual")
                        .WithMany()
                        .HasForeignKey("PasoActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ejecuciones_ejecucion_paso_paso_actual_id");

                    b.Navigation("Caso");

                    b.Navigation("PasoActual");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.EjecucionPaso", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Caso", null)
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejecucion_pasos_casos_caso_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.Ejecucion", "Ejecucion")
                        .WithMany("Pasos")
                        .HasForeignKey("EjecucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ejecucion_pasos_ejecuciones_ejecucion_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoPasoDef", "FlujoPasoDef")
                        .WithMany()
                        .HasForeignKey("FlujoPasoDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejecucion_pasos_flujo_paso_defs_flujo_paso_def_id");

                    b.HasOne("Viariato.Infrastructure.Trabajos.Trabajo", null)
                        .WithMany()
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ejecucion_pasos_trabajos_trabajo_id");

                    b.Navigation("Ejecucion");

                    b.Navigation("FlujoPasoDef");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Evidencia", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.Caso", null)
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evidencias_casos_caso_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.Documento", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_evidencias_documentos_documento_id");

                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", "EjecucionPaso")
                        .WithMany()
                        .HasForeignKey("EjecucionPasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidencias_ejecucion_pasos_ejecucion_paso_id");

                    b.Navigation("EjecucionPaso");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.RevisionHumana", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", "EjecucionPaso")
                        .WithMany()
                        .HasForeignKey("EjecucionPasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revisiones_humanas_ejecucion_pasos_ejecucion_paso_id");

                    b.Navigation("EjecucionPaso");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.RpaEjecucionDetalle", b =>
                {
                    b.HasOne("Viariato.Modules.Casos.Domain.EjecucionPaso", "EjecucionPaso")
                        .WithMany()
                        .HasForeignKey("EjecucionPasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rpa_ejecucion_detalles_ejecucion_pasos_ejecucion_paso_id");

                    b.Navigation("EjecucionPaso");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.AsignacionFlujo", b =>
                {
                    b.HasOne("Viariato.Modules.Flujos.Domain.Flujo", "Flujo")
                        .WithMany()
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_flujo_flujo_flujo_id");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.Flujo", b =>
                {
                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoVersion", "VersionActiva")
                        .WithMany()
                        .HasForeignKey("VersionActivaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_flujos_flujo_version_version_activa_id");

                    b.Navigation("VersionActiva");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoEstadoDef", b =>
                {
                    b.HasOne("Viariato.Modules.Flujos.Domain.Flujo", "Flujo")
                        .WithMany()
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flujo_estado_defs_flujos_flujo_id");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoPasoDef", b =>
                {
                    b.HasOne("Viariato.Modules.Flujos.Domain.AgenteDefinicion", "AgenteDefinicion")
                        .WithMany()
                        .HasForeignKey("AgenteDefinicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_flujo_paso_defs_agente_definiciones_agente_definicion_id");

                    b.HasOne("Viariato.Modules.Flujos.Domain.FlujoVersion", "FlujoVersion")
                        .WithMany("Pasos")
                        .HasForeignKey("FlujoVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flujo_paso_defs_flujo_version_flujo_version_id");

                    b.Navigation("AgenteDefinicion");

                    b.Navigation("FlujoVersion");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoVersion", b =>
                {
                    b.HasOne("Viariato.Modules.Flujos.Domain.Flujo", "Flujo")
                        .WithMany("Versiones")
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flujo_versiones_flujos_flujo_id");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.RefreshToken", b =>
                {
                    b.HasOne("Viariato.Modules.Users.Domain.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_id");

                    b.HasOne("Viariato.Modules.Users.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.RolePermission", b =>
                {
                    b.HasOne("Viariato.Modules.Users.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Viariato.Modules.Users.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.UserRole", b =>
                {
                    b.HasOne("Viariato.Modules.Users.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Viariato.Modules.Users.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viariato.Modules.Casos.Domain.Ejecucion", b =>
                {
                    b.Navigation("Pasos");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.Flujo", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("Viariato.Modules.Flujos.Domain.FlujoVersion", b =>
                {
                    b.Navigation("Pasos");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Viariato.Modules.Users.Domain.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
