<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Viariato.Shared\Viariato.Shared.csproj" />
    <ProjectReference Include="..\Viariato.Infrastructure\Viariato.Infrastructure.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Users\Viariato.Modules.Users.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Markets\Viariato.Modules.Markets.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Ops\Viariato.Modules.Ops.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Flujos\Viariato.Modules.Flujos.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Casos\Viariato.Modules.Casos.csproj" />
    <ProjectReference Include="..\Viariato.Modules.RpaFleet\Viariato.Modules.RpaFleet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.10.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
