<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Viariato.Shared\Viariato.Shared.csproj" />
    <ProjectReference Include="..\Viariato.Infrastructure\Viariato.Infrastructure.csproj" />
    <ProjectReference Include="..\Viariato.Modules.Flujos\Viariato.Modules.Flujos.csproj" />
    <ProjectReference Include="..\Viariato.Modules.RpaFleet\Viariato.Modules.RpaFleet.csproj" />
    <ProjectReference Include="..\Viariato.ApiContracts\Viariato.ApiContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.412.3" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
